image: docker:latest
##
stages:
  - unit-tests
  - build
  - staging-e2e
  - e2e
  - integration
  - integration-clean
  - image-ce-deploy
  - audit

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "OpenSource"
    - if: $CI_COMMIT_TAG

unit-tests:
  stage: unit-tests
  image: ${ALGOTECH_REGISTRY_HOST}/algo-node:18.13.0-alpine
  script:
    - npm install --silent --legacy-peer-deps
    - npm run test:unit
  artifacts:
    when: always
    reports:
      junit: test-reports/junit.xml
  only:
    - OpenSource

integration-tests:
  stage: build
  before_script:
    - apk add --no-cache git bash npm
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
  script:
    - export DATE=$(date +%Y.%-m.%-d)
    - npm --no-git-tag-version version ${DATE}
    - export VERSION=$(cat package.json | grep version | awk '{printf($2)}' | cut -d'"' -f2)
    - echo "Version=${VERSION}"
    - docker build --no-cache -f Dockerfile -t ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce .
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce
    - docker push ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce
    - docker image rm ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce
  needs:
    - job: unit-tests
  only:
    - OpenSource

integration-e2e:
  stage: staging-e2e
  before_script:
    - apk add --no-cache git bash
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
    - git clone ${ALGOTECH_GIT_EXPLOITATION}
    - cd exploitation/CI
  script:
    - cd fixtures/mongo-seed
    - docker build -f Dockerfile -t mongo-seed:${CI_COMMIT_REF_NAME}-ce .
    - cd ../..
    - /bin/bash ci-stack-compose.sh ${CI_COMMIT_REF_NAME}-ce
    - for i in $(cat .env);do export $i;done
    - docker stack deploy --with-registry-auth -c stack-compose.yml ci-p2-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-ce
  needs:
    - job: integration-tests
  only:
    - OpenSource

tests-e2e:
  stage: e2e 
  before_script:
    - apk add --no-cache git bash
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
    - git clone ${ALGOTECH_GIT_EXPLOITATION}
    - cd exploitation/CI
  script:
    - /bin/bash ci-stack-compose.sh ${CI_COMMIT_REF_NAME}-ce
    - export DC_IMG_VERSION="${CI_COMMIT_REF_NAME}-ce"
    - CONTAINER=$(docker ps | grep ci-p2-${CI_PROJECT_NAME}-${DC_IMG_VERSION} | grep vision-server:${DC_IMG_VERSION} | awk '{print $1}')
    - docker exec -t $CONTAINER npm run test:ci
    - docker exec -t $CONTAINER npm run test:prov
  needs:
    - job: integration-e2e
  only:
    - OpenSource

tag-to-registry:
  stage: integration
  before_script:
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
  script:
    - docker tag ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-ce ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:latest-ce
    - docker push ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:latest-ce
  needs:
    - job: tests-e2e
  only:
    - OpenSource

integration-clean:
  stage: integration-clean
  before_script:
    - apk update
    - apk add --no-cache git bash openssh-client
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
    - which ssh-agent
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n "$SSH_CI_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - ssh -o "StrictHostKeyChecking=no" dev-ci@dev.myalgotech.io /data/algotech-infra/run-clean-registry.sh ${CI_PROJECT_NAME} ${CI_COMMIT_REF_NAME}-ce
  when: always
  needs:
    - job: tag-to-registry
  only:
    - OpenSource

dockerhub-image-deploy:
  stage: image-ce-deploy
  before_script:
    - apk add --no-cache git bash
    - docker login -u "${ALGOTECH_REGISTRY_USER}" -p "${ALGOTECH_REGISTRY_PASS}" https://${ALGOTECH_REGISTRY_HOST}
    - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
  script:
    - TAG=${CI_COMMIT_TAG}
    - docker tag ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:latest-ce ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:$TAG
    - docker push ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:$TAG
    - docker tag ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:latest-ce algotechinfo/${CI_PROJECT_NAME}:$TAG
    - docker tag ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:latest-ce algotechinfo/${CI_PROJECT_NAME}:latest
    - docker push algotechinfo/${CI_PROJECT_NAME}:$TAG
    - docker push algotechinfo/${CI_PROJECT_NAME}:latest
  only:
    - tags

####################
# AUDIT CODE

owasp snapshot report:
  stage: audit
  image: 
    name: ${ALGOTECH_REGISTRY_HOST}/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "${ALGOTECH_REGISTRY_USER}"
    TRIVY_PASSWORD: "${ALGOTECH_REGISTRY_PASS}"
    TRIVY_AUTH_URL: "https://${ALGOTECH_REGISTRY_HOST}"
    FULL_IMAGE_NAME: ${ALGOTECH_REGISTRY_HOST}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
  when: manual
  script:
    - trivy --version
    - echo "Analyzing image $FULL_IMAGE_NAME"
    # Builds report 
    - trivy image --exit-code 0 --no-progress "$FULL_IMAGE_NAME" > trivy-report.md
    # Prints full report
    - trivy image --exit-code 0 --no-progress --severity HIGH "$FULL_IMAGE_NAME"
    # Fail on critical vulnerabilities
    - trivy image --exit-code 1 --no-progress --severity CRITICAL  "$FULL_IMAGE_NAME"
  artifacts:
    when: always
    paths:
      - "${CI_PROJECT_DIR}/trivy-report.md"
