/* eslint-disable prettier/prettier */
import { MailerModule } from '@nest-modules/mailer';
import { Module } from '@nestjs/common';
import { HttpModule } from '@nestjs/axios';
import { DatabaseModule } from '../database/database.module';
import { KeycloakService } from './admin/keycloak.service';
import * as providers from './index';
import * as interpretor from './workflow-interpretor/index';

@Module({
    imports: [
        HttpModule.register({
            timeout: 0,
            maxContentLength: Number.MAX_SAFE_INTEGER,
        }),
        DatabaseModule,
        MailerModule,
    ],
    controllers: [],
    providers: [
        providers.SettingsDataService,
        providers.UtilsService,
        providers.NatsService,
        providers.LicenceService,
        providers.CustomerService,
        providers.LokiLogger,
        providers.SearchHead,
        providers.SearchQueryBuilderHead,
        providers.RxExtendService,
        providers.ObservableQueue,
        providers.EmailService,
        providers.GroupService,
        providers.SettingsService,
        providers.UsersService,
        providers.SmartModelsService,
        providers.SmartObjectsService,
        providers.SmartObjectTreeService,
        providers.DatabaseService,
        providers.SmartFlowsService,
        providers.WorkflowInstancesService,
        providers.WorkflowModelsService,
        interpretor.ReportsUtilsService,
        interpretor.ScheduleUtilsService,
        interpretor.SkillsUtilsService,
        interpretor.SmartFlowUtilsService,
        interpretor.SoUtilsService,
        interpretor.SysUtilsService,
        interpretor.TaskUtilsService,
        interpretor.WorkflowAbstractService,
        interpretor.WorkflowBreadCrumbService,
        interpretor.WorkflowDataApiService,
        interpretor.WorkflowDataService,
        interpretor.WorkflowMessageService,
        interpretor.WorkflowProfilesService,
        interpretor.WorkflowReaderService,
        interpretor.WorkflowSaveService,
        interpretor.WorkflowServiceBridgeToHeadService,
        interpretor.WorkflowServiceService,
        interpretor.WorkflowSoService,
        interpretor.WorkflowMetricsService,
        interpretor.WorkflowTaskService,
        interpretor.WorkflowUtilsService,
        interpretor.WorkflowInterpretorService,
        providers.ApplicationModelsService,
        providers.NotificationsService,
        providers.EnvironmentService,
        providers.GenericListsSevice,
        providers.AdminService,
        providers.TagsService,
        providers.SmartNodesService,
        providers.SchedulesService,
        providers.SearchScheduleService,
        providers.SmartTasksLogsService,
        providers.SmartTasksService,
        providers.SmartTasksHead,
        providers.AuthHead,
        providers.CustomerHead,
        providers.GroupHead,
        providers.EmailHead,
        providers.SettingsHead,
        providers.UsersHead,
        providers.SmartModelsHead,
        providers.SmartObjectsHead,
        providers.DatabaseHead,
        providers.SmartFlowsHead,
        providers.WorkflowInstancesHead,
        providers.WorkflowModelsHead,
        providers.GenericListsHead,
        providers.AdminHead,
        providers.AuditTrailHead,
        providers.TagsHead,
        providers.SmartNodesHead,
        providers.ApplicationModelsHead,
        providers.EnvironmentHead,
        providers.NotificationsHead,
        interpretor.WorkflowInterpretorHead,
        providers.SchedulesHead,
        providers.DocumentsHead,
        providers.DocumentsService,
        providers.FilesService,
        providers.FilesHead,
        providers.IconsHead,
        providers.IconService,
        providers.IndexationService,
        providers.RasterHead,
        providers.TemplateHead,
        KeycloakService,
        providers.MetricsHead,
        providers.MetricsService,
        providers.ManifestHead,
        providers.ManifestService,
        providers.OpenAPIGeneratorService,
        providers.ProcessMonitoringHead,
        providers.ProcessMonitoringService,
        providers.I18nHead,
        providers.I18nService,
        providers.MonitorHead,
    ],
    exports: [
        providers.SettingsDataService,
        providers.UtilsService,
        providers.RxExtendService,
        providers.LokiLogger,
        providers.SearchHead,
        providers.SearchQueryBuilderHead,
        providers.NatsService,
        providers.CustomerHead,
        providers.GroupHead,
        providers.EmailHead,
        providers.SettingsHead,
        providers.UsersHead,
        providers.SmartModelsHead,
        providers.SmartObjectsHead,
        providers.DatabaseHead,
        providers.SmartFlowsHead,
        providers.WorkflowInstancesHead,
        providers.WorkflowModelsHead,
        providers.GenericListsHead,
        providers.AdminHead,
        providers.AuditTrailHead,
        interpretor.WorkflowInterpretorHead,
        providers.GenericListsHead,
        providers.TagsHead,
        providers.SmartNodesHead,
        providers.ApplicationModelsHead,
        providers.EnvironmentHead,
        providers.NotificationsHead,
        providers.SchedulesHead,
        providers.SmartTasksHead,
        providers.AuthHead,
        providers.DocumentsHead,
        providers.IconsHead,
        providers.RasterHead,
        providers.TemplateHead,
        providers.FilesHead,
        providers.ProcessMonitoringHead,
        providers.I18nHead,
        providers.MonitorHead,
        KeycloakService,
        providers.MetricsHead,
        providers.MetricsService,
        providers.ManifestHead,
        providers.ManifestService,
        interpretor.WorkflowServiceService,
        providers.OpenAPIGeneratorService,
        interpretor.WorkflowMetricsService,
        
    ],
})
export class ProvidersModule { }
